//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public enum Contact_Address1_FreightTermsCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Бесплатно", 1)]
		Besplatno = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("CIF - стоимость, страхование и фрахт", 2)]
		CIF___stoimost_strahovanie_i_fraht = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("CIP - перевозка и страхование оплачены до", 3)]
		CIP___perevozka_i_strahovanie_oplacheny_do = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("CPT - перевозка оплачена до", 4)]
		CPT___perevozka_oplachena_do = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("DAF - доставка до границы", 5)]
		DAF___dostavka_do_granicy = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("DDP - с оплатой пошлины", 8)]
		DDP___s_oplatoj_poshliny = 10,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("DDU - без уплаты пошлины", 9)]
		DDU___bez_uplaty_poshliny = 11,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("DEQ - доставка с причала", 6)]
		DEQ___dostavka_s_prichala = 8,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("DES - доставка с судна", 7)]
		DES___dostavka_s_sudna = 9,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("EXW - франко-завод", 10)]
		EXW___franko_zavod = 12,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("FAS - франко вдоль борта судна", 11)]
		FAS___franko_vdol_borta_sudna = 13,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("FCA - франко-перевозчик", 12)]
		FCA___franko_perevozchik = 14,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("FOB - франко-борт", 0)]
		FOB___franko_bort = 1,
	}
}